version: "3"

services:
  api:
    build:
      context: api
      dockerfile: ../Dockerfile
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./data/postgres
        target: /data
    ports:
      - 3000:3000
    command: "go run ."
    env_file:
      - .env
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./data/postgres
        target: /var/lib/postgresql/data/
