version: "3"

services:
  api:
    build:
      context: api
      dockerfile: ../Dockerfile
    depends_on:
      - postgres
    ports:
      - 3000:3000
    command: "go run ."
    env_file: .env
  postgres:
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: ./data/postgres
        target: /var/lib/postgresql/data
  test:
    build:
      context: api
      dockerfile: ../Dockerfile
    depends_on:
      - api
    command: "go test -v ./test"
    env_file: .env

volumes:
  pgdata:
    external: true
